### ISSUE TITLE
As a user I want to be able to signup to the game

### ISSUE THREAD

**Issue by rams23** [eficode/pipeline-the-game#10]
In order to signup the user must provide:
* email 
* password
* Role (selecting from a list)
* DevOps maturity (selecting from a list)

The password must respect some criteria:
* at least 8 characters
* should contain at least a number and a letter
* should contain at least an uppercase letter and a lowercase letter

To complete the signup, the user also needs to accept the **Terms and Conditions** and the **Privacy Policy**.

**Comment by rams23** [comment]
Hi @sofusalbertsen ,
Should the Roles and DevOps maturity list be dynamic (stored into the database)? 

In any case, we need the first draft of the list for both.

Moreover, I wrote some possible password requirements, feel free to comment.

**Comment by sofusalbertsen** [comment]
Hey @rams23 
Password req is :ok: 
Roles will come, have forwarded it to Lauri

**Comment by GabrieleMazzola** [comment]
Information about the roles and DevOps maturity (taken from Lauri on Slack):

Here's the list for the **roles**:
- Have budget and make final decisions
- Define requirements and propose solutions
- Influence decision
- Give recommendations
- End user
- Student or potential employee
- Consultant
- Other


Here's the list for the DevOps **maturity**:
- Very mature
- Somewhat mature
- Pretty average, really
- Somewhat immature
- Very immature
- I don't know
- Varies by function or team

**Comment by rams23** [comment]
Missing things:
* make roles and devops dynamic (#32)
* add error translations in form
* set user logged
* start email verification flow (#12)
* check on scam emails(?)
* security rules on firestore
