### ISSUE TITLE
Usability Major - Create Game button is unreachable on Mobile and Narrow desktop screen!

### ISSUE THREAD

**Issue by szilardszell** [eficode/pipeline-the-game#216]
I have two games with two accounts on my screen. And guess what? I can not scroll down to the Buttons!!!! Responsiveness seems not to work on Desktop! This is a Blocker for me!

![image (9)](https://user-images.githubusercontent.com/57249803/108356520-e9004500-71f4-11eb-9673-b94d77c751fd.png)

Similar problem on my mobile screen! 
![Screenshot_20210218-130107_Chrome](https://user-images.githubusercontent.com/57249803/108356543-ee5d8f80-71f4-11eb-9841-d2701bc6f400.jpg)

**Comment by JasmineCrozier** [comment]
I think the animation is really not necessary (it's almost adding confusion, as it makes the user think something could happen when clicking on the cards). Maybe we can save time, and just use an image version of this like in the design app.

**Comment by szilardszell** [comment]
Seeing the original agreement, I see that Mobile was excluded. Is there a possibility to make sure this is clear to the end users, like have a message to them that the Application not supporting Mobile Usage currently? Handling this in some nice way?

"This  web  application  is  also  intended  for  desktopusage  only:it  will  be  used neither    on    tablets    nor    smartphones.    For    the    scope    of    this    MVP, internationalization is not required, and all resources will be in English only"
