### ISSUE TITLE
Usability - Improvement suggestion - Make long notes visible on cards, when hoovering with mouse

### ISSUE THREAD

**Issue by szilardszell** [eficode/pipeline-the-game#220]
If the Note is longer then it fits to the box, show the full text in on mouse hoover. Currently I need to click on the text to read it, but that makes it modifiable (so I can delete the text accidentally, when I just want to read it) (edited) 

![image (12)](https://user-images.githubusercontent.com/57249803/108358245-282f9580-71f7-11eb-98c8-700eb797d59e.png)

**Comment by Alb93** [comment]
As discussed with @Jasmine, going for a show-more like feature on hover could incentivize users to write long text there. Because time estimation should be short, it's better to let you discuss the issue internally
