### ISSUE TITLE
Placeholders on website login

### ISSUE THREAD

**Issue by figaw** [eficode/pipeline-the-game#260]
"Test1234" is not a very good placeholder for a password field.

![image](https://user-images.githubusercontent.com/2676331/111758027-45aa5a80-889c-11eb-9ae6-5f3e5c1725bc.png)

I'll suggest "Password" like e.g. on Twitter.

![image](https://user-images.githubusercontent.com/2676331/111758236-87d39c00-889c-11eb-90f7-c97c06f97bb5.png)

**Comment by figaw** [comment]
It also looks like you need an `@eficode` email to sign up, so `john.doe@example.com` is probably also a better placeholder for the email field.. or simply `Email`.

**Comment by figaw** [comment]
These comments extend to the sign-up page..

![image](https://user-images.githubusercontent.com/2676331/111758527-e862d900-889c-11eb-8a96-89c24ea85f31.png)

**Comment by sofusalbertsen** [comment]
Done, thanks! :+1:
