### ISSUE TITLE
Non-obvious required fields on sign-up page

### ISSUE THREAD

**Issue by figaw** [eficode/pipeline-the-game#261]
"I just want to play the game, why do you ask all these questions."

![image](https://user-images.githubusercontent.com/2676331/111758641-07616b00-889d-11eb-856d-ea401018b1ba.png)

The required fields becomes a roadblock, when there's no asterisk `*` commonly referred to as `* required fields` in the bottom of the page, or simply a small title saying (required) 

![image](https://user-images.githubusercontent.com/2676331/111758890-4c859d00-889d-11eb-88c7-686b80928597.png)

This can be made using the `<small>`-tags.

**Comment by sofusalbertsen** [comment]
Implemented, thanks!
