### ISSUE TITLE
Error "Missing or insufficient permissions." when capital letters are in the email address

### ISSUE THREAD

**Issue by sofusalbertsen** [eficode/pipeline-the-game#275]
Steps to reproduce:
Try to sign up with `Test@eficode.com`
When clicking sign up, your get the error message:
"Missing or insufficient permissions."

Changing it to lowercase solves the problem
![Screenshot from 2021-04-09 07-45-49](https://user-images.githubusercontent.com/4633181/114135406-79abf500-9909-11eb-9941-aa26752100cb.png)

**Comment by rams23** [comment]
@sofusalbertsen firebase internally creates the user token with the lowercase email. While creating a user record in the database we check that the email is the same as the one in the token. #276 forces the email to be lowercase and solves the problem

**Comment by sofusalbertsen** [comment]
Wow that was fast!
Thanks @rams23 !
