### ISSUE TITLE
Gamerule Build Prior to Deploy is in a different font than the rest

### ISSUE THREAD

**Issue by sofusalbertsen** [eficode/pipeline-the-game#277]
![Screenshot from 2021-04-15 12-26-34](https://user-images.githubusercontent.com/4633181/114855102-da45a100-9de5-11eb-93a8-dba9fd9abd11.png)
All other rules looks like the above.

![Screenshot from 2021-04-15 12-25-19](https://user-images.githubusercontent.com/4633181/114855011-bda96900-9de5-11eb-88d9-fe7c270429fe.png)

**Comment by rams23** [comment]
It's an svg image, I'll check it and recreate it if necessary
