### ISSUE TITLE
Define environment variables for all emulators

### ISSUE THREAD

**Issue by GabrieleMazzola** [eficode/pipeline-the-game#61]
As of now, only the variables for the Auth and Firestore emulators are defined and used. We should follow the same approach with all emulators.

**Comment by sofusalbertsen** [comment]
@GaborMegyaszai, @rams23  is this something that is implemented, or will be, or should we close it?

**Comment by GabrieleMazzola** [comment]
@sofusalbertsen, it has not been implemented since it turned out to be not necessary after all. I believe we can close this.
