### ISSUE TITLE
As a PO, I want the game to be scalable (in terms of connected user load)

### ISSUE THREAD

**Issue by rams23** [eficode/pipeline-the-game#83]
shard games across different instances of RTDB

* know the actual load of a RTDB instance ad a given time
* choose the less used instance of the RTDB when entering a game that is not yet assigned (and save the RTDB instance reference into the game Firestore document) and copy the current game state from Firestore to RTDB selected instance
* keep track of the last time a user was in the game
* remove the game from a RTDB instance after a given amount of time from the last usage 
* update the Firestore document with the game state and removing the RTDB assignment

**Comment by Alb93** [comment]
Technical proposal:

a) Save online/offline status (on a game) for every user on each instances of RTDB. 
	-> Follow RTDB procedure
	-> To solve disconnecting issues or similar, put a setInterval function which update the status every x 		seconds (included the timestamp)
	-> Create a job which query for online && status.timestamp < now - y, with y>>x and update to offine and update 		the counter * (this should check also d))
b) Function onUpdate on every status change, to update onlineOnGame (with a RTDB instance reference too) counter on firestore (think about sharding)
c) API entering the game checking the following
	-> Check if it is the first. If so, choose the best RTDB instance through firestore counters and move from firestore to RTDB and write the RTDB instance on firestore document

d) API leaving the game checking the following
	-> Check if it is the last. If so, move from RTDB to Firestore and clear RTDB

**Comment by GabrieleMazzola** [comment]
Suggestion: What about substituting d) with a recurrent Cloud Function that runs every X minutes and moves inactive games (as in inactive for longer than a predefined period of time) from RTDB to Firestore and clears the RTDB?

**Comment by Alb93** [comment]
It's included within 3a)

**Comment by rams23** [comment]
Here are some update after talking with Alberto:
* The API is not called when every user enters the game. When a user joins a game that does not have an RTDB instance linked to it then the API is called and it will initialize the game, linking it to RTDB. Otherwise, if the game is already linked to the RTDB everything can be handled using Firestore.
* here is a possible RTDB data model under the path /games/{gameId}
```code
{
	[cardId]: {
		parent: 'board'|panel',
		position?: {x,y}
		locked(?lockedBy): boolean{useId}?,
		estimation: string;
	},
	boardDimensions:{
		x,
		y
	}
}
```

**Comment by rams23** [comment]
* update common package to remove firebase/admin deps
* investigate on callable functions and remove axios in case
* remove rtdb instance from store using named app
* rename/updtate loadBalancer state
* add onStatusCreate function 
* check on multiple games of the same user in a single rtdbinstace

**Comment by rams23** [comment]
onDisconnect works at database level in a reliable way, so no need for timestamp and cron jobs
